# -*- coding: utf-8 -*-
"""RAGapplication.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hWMTzQT7FYCvu-_Ii5KyPDSATb-b6pKr
"""

from google.colab import drive
drive.mount('/content/drive')



"""# Task
Build a RAG application for "knowledge_base_autism.txt" using Hugging Face models and a vector database, and create a user interface for interacting with the application.

## Load and split the document

### Subtask:
Load the `knowledge_base_autism.txt` file and split it into smaller chunks for processing.

**Reasoning**:
Import necessary libraries, load the text file, split it into chunks, and store the chunks in a variable.
"""

from langchain.document_loaders import TextLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter

# Load the document
# Replace '/path/to/your/knowledge_base_autism.txt' with the actual path to your file in Google Drive
loader = TextLoader("/content/drive/MyDrive/ASD-COLAB/autism/knowledge_base_autism.txt")
documents = loader.load()

# Initialize a text splitter
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)

# Split the document into chunks
document_chunks = text_splitter.split_documents(documents)

# Display the number of chunks and the first chunk
print(f"Number of chunks: {len(document_chunks)}")
print("First chunk:")
print(document_chunks[0].page_content)

pip install -U langchain-community

pip install -U langchain-huggingface

"""## Set up the RAG chain

### Subtask:
Configure a RAG chain that uses a Hugging Face language model and the created vector store to retrieve relevant information and generate answers to user queries.

**Reasoning**:
Import necessary libraries, initialize a Hugging Face language model, create a retriever from the vector store, and set up a RetrievalQA chain.
"""

# Install necessary libraries
!pip install -U transformers

# Install necessary libraries
!pip install -U sentence-transformers faiss-cpu

from langchain_huggingface import HuggingFaceEmbeddings
from langchain.vectorstores import FAISS

# Initialize a Hugging Face embedding model
# You can choose a different model from the Hugging Face model hub
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

# Create embeddings for the document chunks and store them in a FAISS vector store
db = FAISS.from_documents(document_chunks, embeddings)

print("Vector store created successfully!")

from langchain.chains import RetrievalQA
from langchain_huggingface import HuggingFacePipeline
from transformers import pipeline

# Initialize a Hugging Face language model
# You can choose a different model from the Hugging Face model hub
# Consider a smaller model like 'google/flan-t5-small' if memory is an issue
generator = pipeline("text2text-generation", model="google/flan-t5-base")

llm = HuggingFacePipeline(pipeline=generator)

# Create a retriever from the FAISS vector store
retriever = db.as_retriever(search_kwargs={"k": 3})

# Set up the RetrievalQA chain
qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=retriever,
    chain_type="stuff"  # You can experiment with other chain types like "map_reduce" or "refine"
)

print("RAG chain set up successfully!")



# Simple Q&A in the notebook
query = input("Enter your query about autism: ")

if query:
    # Assuming qa_chain is already defined from previous steps
    response = qa_chain.invoke(query)
    print("\nResponse:")
    print(response['result']) # Assuming the response structure has a 'result' key

# Simple Q&A in the notebook
query = input("Enter your query about autism: ")

if query:
    # Assuming qa_chain is already defined from previous steps
    response = qa_chain.invoke(query)
    print("\nResponse:")
    print(response['result']) # Assuming the response structure has a 'result' key